import type * as sqlTypes from "mssql";
import type * as configTypes from "../types/configTypes";
export declare function getProperty(propertyName: "application.httpPort"): number;
export declare function getProperty(propertyName: "application.https"): configTypes.ConfigHTTPSConfig;
export declare function getProperty(propertyName: "reverseProxy.disableCompression"): boolean;
export declare function getProperty(propertyName: "reverseProxy.disableEtag"): boolean;
export declare function getProperty(propertyName: "reverseProxy.blockViaXForwardedFor"): boolean;
export declare function getProperty(propertyName: "reverseProxy.urlPrefix"): "";
export declare function getProperty(propertyName: "mssqlConfig"): sqlTypes.config;
export declare function getProperty(propertyName: "orderNumberFunction"): () => string;
export declare function getProperty(propertyName: "site.header.backgroundColorClass"): () => string;
export declare function getProperty(propertyName: "site.footer.isVisible"): () => boolean;
export declare function getProperty(propertyName: "site.footer.backgroundColorClass"): () => string;
export declare function getProperty(propertyName: "site.footer.textColorClass"): () => string;
export declare function getProperty(propertyName: "site.footer.footerEjs"): () => string;
export declare function getProperty(propertyName: "views.products.title"): () => string;
export declare function getProperty(propertyName: "views.checkout.title"): () => string;
export declare function getProperty(propertyName: "views.checkout_shipping.title"): () => string;
export declare function getProperty(propertyName: "views.toPayment.headerEjs"): () => string;
export declare function getProperty(propertyName: "views.order.title"): () => string;
export declare function getProperty(propertyName: "views.order.headerEjs"): () => string;
export declare function getProperty(propertyName: "currency.code"): () => string;
export declare function getProperty(propertyName: "currency.currencyName"): () => string;
export declare function getProperty(propertyName: "store"): configTypes.StoreConfigs;
export declare function getProperty(propertyName: "store.storeType"): configTypes.StoreTypes;
export declare function getProperty(propertyName: "fees"): Record<string, configTypes.ConfigFeeDefinition>;
export declare function getProperty(propertyName: "products"): Record<string, configTypes.ConfigProduct>;
export declare function getProperty(propertyName: "productHandlers"): configTypes.ProductHandlers[];
export declare function getProperty(propertyName: "settings.checkout_includeCaptcha"): boolean;
export declare function overrideProperty(propertyName: "reverseProxy.urlPrefix", propertyValue: string): void;
export declare function getClientSideProduct(productSKU: string): configTypes.ConfigProduct;
