version: "2"
checks:
  method-complexity:
    config:
      threshold: 12
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 200
  return-statements:
    config:
      threshold: 6
